models:
  author:
    max_name: 150
    max_phone: 11
  book:
    max_name: 150
    year_max: 100
    year_min: 1
  category:
    max_name: 150
  publisher:
    max_name: 150
    max_phone: 11
  user:
    max_name: 150
    max_phone: 11
    max_email: 50
    min_pass: 8
per_page:
  categories: 5
  authors: 5
  publishers: 5
  users: 5
  books: 5
  book: 8
  requests: 5
unit_price: 0.1
unit_day: 1
